[package]
name = "rust-observation-CA"
version = "0.1.0"
authors = ["Théo Plénet <theo.plenet@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayfire = "3.8"